name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - run: npm run build
    
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: -c "serverless plugin install --name serverless-s3-deploy && serverless plugin install --name serverless-cloudfront-invalidate && serverless deploy"
        entrypoint: /bin/sh
      env:
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
